# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backup_media_file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x61\x63kup_media_file.proto\x12!org.calyxos.backup.storage.backup\"\xc3\x02\n\x0f\x42\x61\x63kupMediaFile\x12J\n\x04type\x18\x01 \x01(\x0e\x32<.org.calyxos.backup.storage.backup.BackupMediaFile.MediaType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x15\n\rlast_modified\x18\x04 \x01(\x03\x12\x1a\n\x12owner_package_name\x18\x05 \x01(\t\x12\x13\n\x0bis_favorite\x18\x06 \x01(\x08\x12\x0c\n\x04size\x18\x07 \x01(\x03\x12\x0e\n\x06volume\x18\x08 \x01(\t\x12\x11\n\tchunk_ids\x18\t \x03(\t\x12\x11\n\tzip_index\x18\n \x01(\x05\"<\n\tMediaType\x12\n\n\x06IMAGES\x10\x00\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05\x41UDIO\x10\x02\x12\r\n\tDOWNLOADS\x10\x03\x42\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_media_file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _BACKUPMEDIAFILE._serialized_start=63
  _BACKUPMEDIAFILE._serialized_end=386
  _BACKUPMEDIAFILE_MEDIATYPE._serialized_start=326
  _BACKUPMEDIAFILE_MEDIATYPE._serialized_end=386
# @@protoc_insertion_point(module_scope)
