# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backup_snapshot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import backup_media_file_pb2 as backup__media__file__pb2
from . import backup_document_file_pb2 as backup__document__file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61\x63kup_snapshot.proto\x12!org.calyxos.backup.storage.backup\x1a\x17\x62\x61\x63kup_media_file.proto\x1a\x1a\x62\x61\x63kup_document_file.proto\"\xfb\x01\n\x0e\x42\x61\x63kupSnapshot\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12G\n\x0bmedia_files\x18\x03 \x03(\x0b\x32\x32.org.calyxos.backup.storage.backup.BackupMediaFile\x12M\n\x0e\x64ocument_files\x18\x04 \x03(\x0b\x32\x35.org.calyxos.backup.storage.backup.BackupDocumentFile\x12\x0c\n\x04size\x18\x05 \x01(\x03\x12\x12\n\ntime_start\x18\x06 \x01(\x03\x12\x10\n\x08time_end\x18\x07 \x01(\x03\x42\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_snapshot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _BACKUPSNAPSHOT._serialized_start=114
  _BACKUPSNAPSHOT._serialized_end=365
# @@protoc_insertion_point(module_scope)
